#!/bin/bash

# define path
export bPack_Directory=${0/\/bpack/}
export ProjectDirectory=$(pwd)

# include core module
source "$bPack_Directory/console/console_basic.sh"

# include additional module
require console.message
require bpack.func
require locale.en

# start processing
section_break

# if give only module like init

if [ -n "$2" ]; then
	require_filename="bpack.$1.$2"
	shift 2
else
	require_filename="bpack.$1"
	shift
fi

require $require_filename $@

# if file not exists, go help
if [ $? -eq 0 ]; then
	require "bpack.help"
fi

# end 
section_break
